spring:
  application:
    name: spring-batch
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/orclpdb
      username: hr
      password: hr
      driver-class-name: oracle.jdbc.OracleDriver
      pool-name: TwoMasterDBPool
      auto-commit: false
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM dual
      max-lifetime: 120000
